version: '3'

services:
  generator:
    image: app7ware.azurecr.io/gen:ci-${GENERATOR_BUILD_NUMBER-15}
    ports:
      - "8080:80"
  mail:
    image: mailhog/mailhog
    ports:
      - "8081:8025"

  