version: '3.1'

services:
  generator:
    image: app7ware.azurecr.io/gen:ci-${GENERATOR_BUILD_NUMBER-19}
    #ports:
    #  - "8080:80"
  mail:
    image: mailhog/mailhog
    #ports:
    #  - "8025:8025"
    #  - "1025:1025"
  integration:
    image: app7ware.azurecr.io/gen:integration-${BUILD_NUMBER-19}
    build: .
    environment:
      - TEAMCITY_PROJECT_NAME